# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: simplify_dev
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000
  template: template0
  
test:
  adapter: postgresql
  database: simplify_test
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: simplify_prod
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000
  template: template0
